/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Todo API
 * OpenAPI spec version: 1.0.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import {customInstance} from './client';
import type {ErrorType, BodyType} from './client';
export interface Tokens {
  refreshToken: string;
  accessToken: string;
}

export interface TodoRequest {
  title: string;
  description?: string;
}

export interface TodoResponse {
  id: string;
  title: string;
  userId: string;
  completed: boolean;
  createdAt: string;
  description?: string;
}

export interface User {
  username: string;
  password: string;
}

export interface UserResponse {
  id: string;
  username: string;
  createdAt: string;
}

export type RefreshTokenBody = {
  refreshToken: string;
};

export type RefreshToken200 = {
  /** The newly generated access token. */
  accessToken?: string;
};

export type GetTodoList200 = {
  todos: TodoResponse[];
};

/**
 * @summary Register a new user
 */
export const registerUser = (user: BodyType<User>, signal?: AbortSignal) =>
  customInstance<Tokens>({
    url: `/api/register`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: user,
    signal,
  });

export const getRegisterUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    {data: BodyType<User>},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  {data: BodyType<User>},
  TContext
> => {
  const mutationKey = ['registerUser'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    {data: BodyType<User>}
  > = (props) => {
    const {data} = props ?? {};

    return registerUser(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>;
export type RegisterUserMutationBody = BodyType<User>;
export type RegisterUserMutationError = ErrorType<unknown>;

/**
 * @summary Register a new user
 */
export const useRegisterUser = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerUser>>,
      TError,
      {data: BodyType<User>},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  {data: BodyType<User>},
  TContext
> => useMutation(getRegisterUserMutationOptions(options), queryClient);

/**
 * @summary User login
 */
export const loginUser = (user: BodyType<User>, signal?: AbortSignal) =>
  customInstance<Tokens>({
    url: `/api/login`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: user,
    signal,
  });

export const getLoginUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    {data: BodyType<User>},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  {data: BodyType<User>},
  TContext
> => {
  const mutationKey = ['loginUser'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    {data: BodyType<User>}
  > = (props) => {
    const {data} = props ?? {};

    return loginUser(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>;
export type LoginUserMutationBody = BodyType<User>;
export type LoginUserMutationError = ErrorType<unknown>;

/**
 * @summary User login
 */
export const useLoginUser = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginUser>>,
      TError,
      {data: BodyType<User>},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  {data: BodyType<User>},
  TContext
> => useMutation(getLoginUserMutationOptions(options), queryClient);

/**
 * Refresh the access token using a valid refresh token.
 * @summary Refresh Access Token
 */
export const refreshToken = (refreshTokenBody: BodyType<RefreshTokenBody>, signal?: AbortSignal) =>
  customInstance<RefreshToken200>({
    url: `/api/refresh-token`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: refreshTokenBody,
    signal,
  });

export const getRefreshTokenMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    {data: BodyType<RefreshTokenBody>},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  {data: BodyType<RefreshTokenBody>},
  TContext
> => {
  const mutationKey = ['refreshToken'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshToken>>,
    {data: BodyType<RefreshTokenBody>}
  > = (props) => {
    const {data} = props ?? {};

    return refreshToken(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>;
export type RefreshTokenMutationBody = BodyType<RefreshTokenBody>;
export type RefreshTokenMutationError = ErrorType<unknown>;

/**
 * @summary Refresh Access Token
 */
export const useRefreshToken = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshToken>>,
      TError,
      {data: BodyType<RefreshTokenBody>},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  {data: BodyType<RefreshTokenBody>},
  TContext
> => useMutation(getRefreshTokenMutationOptions(options), queryClient);

/**
 * Get the currently authenticated user's information.
 * @summary Get current user
 */
export const getCurrentUser = (signal?: AbortSignal) =>
  customInstance<UserResponse>({url: `/api/user/me`, method: 'GET', signal});

export const getGetCurrentUserQueryKey = () => [`/api/user/me`] as const;

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({signal}) =>
    getCurrentUser(signal);

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
export type GetCurrentUserQueryError = ErrorType<void>;

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get current user
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return {...query, queryKey: queryOptions.queryKey};
}

/**
 * @summary Get the list of todos
 */
export const getTodoList = (signal?: AbortSignal) =>
  customInstance<GetTodoList200>({url: `/api/todo/list`, method: 'GET', signal});

export const getGetTodoListQueryKey = () => [`/api/todo/list`] as const;

export const getGetTodoListQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>>;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodoListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoList>>> = ({signal}) =>
    getTodoList(signal);

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getTodoList>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetTodoListQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoList>>>;
export type GetTodoListQueryError = ErrorType<unknown>;

export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoList>>,
          TError,
          Awaited<ReturnType<typeof getTodoList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoList>>,
          TError,
          Awaited<ReturnType<typeof getTodoList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get the list of todos
 */

export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
  const queryOptions = getGetTodoListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return {...query, queryKey: queryOptions.queryKey};
}

/**
 * @summary Get a specific todo by ID
 */
export const getTodoById = (id: string, signal?: AbortSignal) =>
  customInstance<TodoResponse>({url: `/api/todo/${id}`, method: 'GET', signal});

export const getGetTodoByIdQueryKey = (id: string) => [`/api/todo/${id}`] as const;

export const getGetTodoByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodoById>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoById>>, TError, TData>>;
  }
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodoByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoById>>> = ({signal}) =>
    getTodoById(id, signal);

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getTodoById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetTodoByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoById>>>;
export type GetTodoByIdQueryError = ErrorType<unknown>;

export function useGetTodoById<
  TData = Awaited<ReturnType<typeof getTodoById>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoById>>,
          TError,
          Awaited<ReturnType<typeof getTodoById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetTodoById<
  TData = Awaited<ReturnType<typeof getTodoById>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoById>>,
          TError,
          Awaited<ReturnType<typeof getTodoById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetTodoById<
  TData = Awaited<ReturnType<typeof getTodoById>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get a specific todo by ID
 */

export function useGetTodoById<
  TData = Awaited<ReturnType<typeof getTodoById>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
  const queryOptions = getGetTodoByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return {...query, queryKey: queryOptions.queryKey};
}

/**
 * @summary Delete a todo by ID
 */
export const deleteTodoById = (id: string, signal?: AbortSignal) =>
  customInstance<void>({url: `/api/todo/${id}`, method: 'DELETE', signal});

export const getDeleteTodoByIdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTodoById>>,
    TError,
    {id: string},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTodoById>>,
  TError,
  {id: string},
  TContext
> => {
  const mutationKey = ['deleteTodoById'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodoById>>, {id: string}> = (
    props
  ) => {
    const {id} = props ?? {};

    return deleteTodoById(id);
  };

  return {mutationFn, ...mutationOptions};
};

export type DeleteTodoByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodoById>>>;

export type DeleteTodoByIdMutationError = ErrorType<unknown>;

/**
 * @summary Delete a todo by ID
 */
export const useDeleteTodoById = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTodoById>>,
      TError,
      {id: string},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteTodoById>>, TError, {id: string}, TContext> =>
  useMutation(getDeleteTodoByIdMutationOptions(options), queryClient);

/**
 * @summary Update a todo by ID
 */
export const updateTodoById = (
  id: string,
  todoRequest: BodyType<TodoRequest>,
  signal?: AbortSignal
) =>
  customInstance<TodoResponse>({
    url: `/api/todo/${id}`,
    method: 'PUT',
    headers: {'Content-Type': 'application/json'},
    data: todoRequest,
    signal,
  });

export const getUpdateTodoByIdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTodoById>>,
    TError,
    {id: string; data: BodyType<TodoRequest>},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTodoById>>,
  TError,
  {id: string; data: BodyType<TodoRequest>},
  TContext
> => {
  const mutationKey = ['updateTodoById'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTodoById>>,
    {id: string; data: BodyType<TodoRequest>}
  > = (props) => {
    const {id, data} = props ?? {};

    return updateTodoById(id, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type UpdateTodoByIdMutationResult = NonNullable<Awaited<ReturnType<typeof updateTodoById>>>;
export type UpdateTodoByIdMutationBody = BodyType<TodoRequest>;
export type UpdateTodoByIdMutationError = ErrorType<unknown>;

/**
 * @summary Update a todo by ID
 */
export const useUpdateTodoById = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTodoById>>,
      TError,
      {id: string; data: BodyType<TodoRequest>},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateTodoById>>,
  TError,
  {id: string; data: BodyType<TodoRequest>},
  TContext
> => useMutation(getUpdateTodoByIdMutationOptions(options), queryClient);

/**
 * @summary Create a new todo
 */
export const createTodo = (todoRequest: BodyType<TodoRequest>, signal?: AbortSignal) =>
  customInstance<TodoResponse>({
    url: `/api/todo`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: todoRequest,
    signal,
  });

export const getCreateTodoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTodo>>,
    TError,
    {data: BodyType<TodoRequest>},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTodo>>,
  TError,
  {data: BodyType<TodoRequest>},
  TContext
> => {
  const mutationKey = ['createTodo'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTodo>>,
    {data: BodyType<TodoRequest>}
  > = (props) => {
    const {data} = props ?? {};

    return createTodo(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type CreateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof createTodo>>>;
export type CreateTodoMutationBody = BodyType<TodoRequest>;
export type CreateTodoMutationError = ErrorType<unknown>;

/**
 * @summary Create a new todo
 */
export const useCreateTodo = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTodo>>,
      TError,
      {data: BodyType<TodoRequest>},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createTodo>>,
  TError,
  {data: BodyType<TodoRequest>},
  TContext
> => useMutation(getCreateTodoMutationOptions(options), queryClient);

/**
 * @summary Mark a todo as complete
 */
export const markTodoComplete = (id: string, signal?: AbortSignal) =>
  customInstance<void>({url: `/api/todo/${id}/complete`, method: 'POST', signal});

export const getMarkTodoCompleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markTodoComplete>>,
    TError,
    {id: string},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markTodoComplete>>,
  TError,
  {id: string},
  TContext
> => {
  const mutationKey = ['markTodoComplete'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof markTodoComplete>>, {id: string}> = (
    props
  ) => {
    const {id} = props ?? {};

    return markTodoComplete(id);
  };

  return {mutationFn, ...mutationOptions};
};

export type MarkTodoCompleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof markTodoComplete>>
>;

export type MarkTodoCompleteMutationError = ErrorType<unknown>;

/**
 * @summary Mark a todo as complete
 */
export const useMarkTodoComplete = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markTodoComplete>>,
      TError,
      {id: string},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof markTodoComplete>>,
  TError,
  {id: string},
  TContext
> => useMutation(getMarkTodoCompleteMutationOptions(options), queryClient);

/**
 * @summary Mark a todo as incomplete
 */
export const markTodoIncomplete = (id: string, signal?: AbortSignal) =>
  customInstance<void>({url: `/api/todo/${id}/incomplete`, method: 'POST', signal});

export const getMarkTodoIncompleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markTodoIncomplete>>,
    TError,
    {id: string},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markTodoIncomplete>>,
  TError,
  {id: string},
  TContext
> => {
  const mutationKey = ['markTodoIncomplete'];
  const {mutation: mutationOptions} = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markTodoIncomplete>>,
    {id: string}
  > = (props) => {
    const {id} = props ?? {};

    return markTodoIncomplete(id);
  };

  return {mutationFn, ...mutationOptions};
};

export type MarkTodoIncompleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof markTodoIncomplete>>
>;

export type MarkTodoIncompleteMutationError = ErrorType<unknown>;

/**
 * @summary Mark a todo as incomplete
 */
export const useMarkTodoIncomplete = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markTodoIncomplete>>,
      TError,
      {id: string},
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof markTodoIncomplete>>,
  TError,
  {id: string},
  TContext
> => useMutation(getMarkTodoIncompleteMutationOptions(options), queryClient);
